### ISSUE TITLE
Doctave 0.4.2 — collapsible sections (default collapsed)

### ISSUE THREAD

**Issue by gastongouron** [Doctave/doctave#58]
Hello, 

Thank you for the amazing project, it's blazing fast and simple, exactly what we were looking for.
I'm wondering if it's something in order to have default sections collapsed rather than opened.

for example, i see on the docs that each sections displays its children once the user clicks on it while on my end, there are open by default.

Currently, I used the following doctave.yaml:

```
---
title: "my company"
version: 1
colors:
  main: "#6875f5"
  main_dark: "#7B8FFE"
  bg: "#FFFFFF"
  bg_dark: "#F8FAFC"

logo: assets/logo.png

navigation:
  - path: docs/bienvenue.md

  - path: docs/Fonctionnalites
    children:
      - path: docs/Fonctionnalites/qa.md
      - path: docs/Fonctionnalites/creation.md
      - path: docs/Fonctionnalites/modification.md
      - path: docs/Fonctionnalites/suppression.md
      - path: docs/Fonctionnalites/lecture.md            
      - path: docs/Fonctionnalites/transferts.md

  - path: docs/Interface
    children:
      - path: docs/Interface/connexion.md
      - path: docs/Interface/security.md
      - path: docs/Interface/dashboard.md
      - path: docs/Interface/agents.md
      - path: docs/Interface/calendars.md
      - path: docs/Interface/calls.md

  - path: docs/Infra     
    children:
      - path: docs/Infra/telecoms.md
      - path: docs/Infra/infrastructure.md
      - path: docs/Infra/couts.md

  - path: docs/Legal    
    children:
      - path: docs/Legal/libertes.md
      - path: docs/Legal/rgpd.md
      - path: docs/Legal/ria.md


```
Let me know if there is a specific parameter or any other workaround to have default collapsed sections. I have been running all around docs and tried various approaches but I cannot find any way to make that happen.

Sincerely

Paul
